---
- name: Load variables for the target system
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family | lower }}.yml"
    - default.yml

- name: Set apt to use https
  become: yes
  apt:
    name: apt-transport-https
    state: present

- include_tasks: install-dotnet-core.yml
